#!/bin/bash
set -ex
cd $HOME

export PATH=/opt/helpers:$PATH
export PATH=/scripts:$PATH
sudo chown -R user /home/user/src/mycroft-gui || true

build-kde-dependencies --withProject kconfig kcoreaddons kguiaddons ki18n kirigami
build-cmake lottie-qml https://github.com/kbroulik/lottie-qml

APK_ARGS=`get-apk-args mycroft-gui`
build-cmake mycroft-gui "<irrelevant>" -DCMAKE_BUILD_TYPE=Debug $APK_ARGS $@
create-apk mycroft-gui
