#!/bin/bash
set -ex
cd $HOME

export PATH=/opt/helpers:$PATH
export PATH=/scripts:$PATH
sudo chown -R user /home/user/src/mycroft-gui || true

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

build-kde-dependencies --withProject kconfig kcoreaddons kguiaddons ki18n kirigami
build-cmake lottie-qml https://github.com/kbroulik/lottie-qml
GIT_EXTRA="--branch 5.15.0" build-qt qtlocation git://code.qt.io/qt/qtlocation.git

APK_ARGS=`python3 /opt/helpers/get-apk-args.py /home/user/src/mycroft-gui`
build-cmake mycroft-gui "<irrelevant>" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON $APK_ARGS $@
create-apk mycroft-gui
